server:
  port: 8815

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: mongodb_test
      authentication-database: springboot_test
      field-naming-strategy: org.springframework.data.mapping.model.CamelCaseAbbreviatingFieldNamingStrategy
