
#数据库配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot-mybatis?serverTimezone=UTC
    username: root
    password: root

#端口号
server:
  port: 8805