
#demo
com:
  liuqiang:
    name: liuqiang
    version: 3.0
    address: 陕西省宝鸡市眉县横渠镇跑安村044号

#person
person:
  liuqiang:
    person-name: liuqiang132
    email: 1695303398@qq.com
    address: 陕西省宝鸡市眉县横渠镇跑安村044号