#

#数据库
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/ssmp?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
      username: root
      password: root
server:
  port: 8811